#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile; then
    dpkg-maintscript-helper rm_conffile /etc/init.d/tmux-cleanup 1.4-6 -- "$@"
fi

if [ "$1" = "remove" ]; then
    remove-shell /usr/bin/tmux
fi

#DEBHELPER#
