#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile; then
    dpkg-maintscript-helper rm_conffile /etc/init.d/tmux-cleanup 1.4-6 -- "$@"
fi

if [ "$1" = "configure" ]; then
    if [ -z "$2" ] || dpkg --compare-versions "$2" lt "1.6~svn2608-2"; then
	add-shell /usr/bin/tmux
    fi
fi

#DEBHELPER#
